language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PINS="lwt.dev:https://github.com/mirage/lwt.git#tracing mirage-profile:https://github.com/mirage/mirage-profile.git#v0.6"
    - WITH_TRACING=1
  matrix:
    - OCAML_VERSION=4.02
      POST_INSTALL_HOOK="make MODE=unix && make clean"
    - OCAML_VERSION=4.02
      UPDATE_GCC_BINUTILS=1
      POST_INSTALL_HOOK="make MODE=xen  && make clean"
